language: go
sudo: required
dist: xenial
go:
  - 1.11.x

before_script: 
  - mysqld --defaults-file=intergration/my3306.cnf --initialize-insecure 
  - mysqld --defaults-file=intergration/my3306.cnf &
  - mysqld --defaults-file=intergration/my3307.cnf --initialize-insecure 
  - mysqld --defaults-file=intergration/my3307.cnf &
  - mysqld --defaults-file=intergration/my3309.cnf --initialize-insecure
  - mysqld --defaults-file=intergration/my3309.cnf &
  - mysqld --defaults-file=intergration/my3310.cnf --initialize-insecure
  - mysqld --defaults-file=intergration/my3310.cnf &
  - make
  - mkdir -p bin/bin/radon-meta
  - cp intergration/backend.json bin/bin/radon-meta/
  - cd ./bin
  - ./radon -c ../conf/radon.default.json &
  - cd ..

before_install:

script:
  #test is used for make testcanal in shift
  - mysql -uroot -P3306 -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS test;'
  - make test
  - make coverage
  # testshift is used for make test on shift. We take it out alone because it needs to build at
  # least three mysql instances, so we just test it on ci. Of course you can build a test env on your machine.
  - make testshift


# integration_test is used to do integrate test on radondb 
  - cd intergration/radon-test
  - bash mtr.sh
  - cd -

after_success:
  # send coverage reports to Codecov
  - bash <(curl -s https://codecov.io/bash) -f "!mock.go"
